#!/bin/sh
# 522 byte pstree @robzr
getKids () { fgrep PPid: /proc/[0-9]*/status 2>/dev/null | sed -n "/\t$1$/s#^/proc/\([0-9]*\).*\$#\1#p" ; }
printKids () {
  [ $1 = 0 ] && return
  [ $1 != 1 ] && echo -n --
  printf %5s:\  $1
  tr \\0 \  </proc/$1/cmdline
  echo
  [ $1 = $$ ] && return
  lastKid=0
  for kid in `getKids $1 | sort -n` ; do
    printKids $lastKid | sed -n '/[0-9]:/s/^/    |/p'
    lastKid=$kid
  done
  printKids $lastKid | sed -n '/[0-9]:/s/^/    L/p'
  echo '  '
}
printKids 1 | sed 's/L    /     /g'
